In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings = pd.read_csv('/Users/rafaellaporto/BeCode/what-should-i-wacth/data.tsv', sep='\t')
tbasics = pd.read_csv('/Users/rafaellaporto/BeCode/what-should-i-wacth/data-5.tsv', sep='\t', low_memory=False)

In [3]:
tbasics_movies = tbasics[tbasics.titleType == 'movie']

tbasics_movies = tbasics_movies[tbasics_movies.isAdult == '0']

tbasics_movies = tbasics_movies.drop(['originalTitle', 'titleType', 'isAdult', 'endYear'], axis=1)

In [4]:
# merge tbasics_movies and ratings on tconst
tbasics_movies = tbasics_movies.merge(ratings, on='tconst')
tbasics_movies = tbasics_movies.set_index('tconst')

In [5]:
tbasics_movies.startYear = tbasics_movies.startYear.replace('\\N', np.NaN).astype(float)

tbasics_movies.runtimeMinutes = tbasics_movies.runtimeMinutes.replace('\\N', np.NaN).astype(float)

In [6]:
tbasics_movies = pd.concat([tbasics_movies.drop('genres', 1), tbasics_movies['genres'].str.get_dummies(sep=",").add_prefix('genre_').astype(bool)], 1)

/var/folders/rl/70187qg15jqf1pwjg83vbsqw0000gn/T/ipykernel_26144/1594438784.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  tbasics_movies = pd.concat([tbasics_movies.drop('genres', 1), tbasics_movies['genres'].str.get_dummies(sep=",").add_prefix('genre_').astype(bool)], 1)
/var/folders/rl/70187qg15jqf1pwjg83vbsqw0000gn/T/ipykernel_26144/1594438784.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  tbasics_movies = pd.concat([tbasics_movies.drop('genres', 1), tbasics_movies['genres'].str.get_dummies(sep=",").add_prefix('genre_').astype(bool)], 1)

In [7]:
tbasics_movies

,primaryTitle,startYear,runtimeMinutes,averageRating,numVotes,genre_Action,genre_Adult,genre_Adventure,genre_Animation,genre_Biography,...,genre_Reality-TV,genre_Romance,genre_Sci-Fi,genre_Short,genre_Sport,genre_Talk-Show,genre_Thriller,genre_War,genre_Western,genre_\N
tconst,,,,,,,,,,,,,,,,,,,,,
tt0000009,Miss Jerry,1894.0,45.0,5.3,200,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
tt0000502,Bohemios,1905.0,100.0,4.2,14,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
tt0000574,The Story of the Kelly Gang,1906.0,70.0,6.0,797,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
tt0000591,The Prodigal Son,1907.0,90.0,5.1,20,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
tt0000615,Robbery Under Arms,1907.0,NaN,4.3,23,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt9916270,Il talento del calabrone,2020.0,84.0,5.8,1378,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
tt9916362,Coven,2020.0,92.0,6.4,5013,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
tt9916428,The Secret of China,2019.0,NaN,3.8,14,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
tt9916538,Kuambil Lagi Hatiku,2019.0,123.0,8.3,6,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
tt9916730,6 Gunn,2017.0,116.0,8.0,8,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [8]:
tbasics_movies = tbasics_movies.drop(['genre_\\N'], axis=1)

In [9]:
tbasics_movies = tbasics_movies.dropna(subset=['startYear', 'runtimeMinutes'])

In [10]:
tbasics_movies.shape

(252233, 33)

In [11]:
tbasics_movies[tbasics_movies['genre_Adult'] == True].count()

primaryTitle         37
startYear            37
runtimeMinutes       37
averageRating        37
numVotes             37
genre_Action         37
genre_Adult          37
genre_Adventure      37
genre_Animation      37
genre_Biography      37
genre_Comedy         37
genre_Crime          37
genre_Documentary    37
genre_Drama          37
genre_Family         37
genre_Fantasy        37
genre_Film-Noir      37
genre_Game-Show      37
genre_History        37
genre_Horror         37
genre_Music          37
genre_Musical        37
genre_Mystery        37
genre_News           37
genre_Reality-TV     37
genre_Romance        37
genre_Sci-Fi         37
genre_Short          37
genre_Sport          37
genre_Talk-Show      37
genre_Thriller       37
genre_War            37
genre_Western        37
dtype: int64

In [12]:
drop_true = [True]
adult = tbasics_movies[tbasics_movies['genre_Adult'].isin(drop_true)]
tbasics_movies.drop(adult.index, axis=0,inplace=True)
# tbasics_movies.drop(delIndex, axis=0)

In [13]:
tbasics_movies[tbasics_movies['genre_Adult'] == True]

Empty DataFrame
Columns: [primaryTitle, startYear, runtimeMinutes, averageRating, numVotes, genre_Action, genre_Adult, genre_Adventure, genre_Animation, genre_Biography, genre_Comedy, genre_Crime, genre_Documentary, genre_Drama, genre_Family, genre_Fantasy, genre_Film-Noir, genre_Game-Show, genre_History, genre_Horror, genre_Music, genre_Musical, genre_Mystery, genre_News, genre_Reality-TV, genre_Romance, genre_Sci-Fi, genre_Short, genre_Sport, genre_Talk-Show, genre_Thriller, genre_War, genre_Western]
Index: []

[0 rows x 33 columns]

In [14]:
# convert startYear, runtimeMinutes to int
tbasics_movies.startYear = tbasics_movies.startYear.astype(np.int16)
tbasics_movies.runtimeMinutes = tbasics_movies.runtimeMinutes.astype(np.int32)
tbasics_movies.numVotes = tbasics_movies.numVotes.astype(np.int32)
tbasics_movies.averageRating = tbasics_movies.averageRating.astype(np.float16)

In [15]:
tbasics_movies.dtypes

primaryTitle          object
startYear              int16
runtimeMinutes         int32
averageRating        float16
numVotes               int32
genre_Action            bool
genre_Adult             bool
genre_Adventure         bool
genre_Animation         bool
genre_Biography         bool
genre_Comedy            bool
genre_Crime             bool
genre_Documentary       bool
genre_Drama             bool
genre_Family            bool
genre_Fantasy           bool
genre_Film-Noir         bool
genre_Game-Show         bool
genre_History           bool
genre_Horror            bool
genre_Music             bool
genre_Musical           bool
genre_Mystery           bool
genre_News              bool
genre_Reality-TV        bool
genre_Romance           bool
genre_Sci-Fi            bool
genre_Short             bool
genre_Sport             bool
genre_Talk-Show         bool
genre_Thriller          bool
genre_War               bool
genre_Western           bool
dtype: object

In [16]:
tbasics_movies.memory_usage(deep=True).sum() / 1024**2

43.63777542114258

In [17]:
tbasics_movies.to_csv('clean_data.csv')